<?xml version="1.0"?>
<!DOCTYPE gdpapers [
<!ELEMENT gdpapers (paper+)>
<!ELEMENT paper (id,title,author+,institution*,cites*,citedby*,year)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT institution (#PCDATA)>
<!ELEMENT cites (#PCDATA)>
<!ELEMENT citedby (#PCDATA)>
<!ELEMENT year (#PCDATA)>
]>
<gdpapers>
	<paper>
		<id>10.1007/3-540-44541-2_11</id>
		<title>2D-Structure Drawings of Similar Molecules</title>
		<author>J. D. Boissonnat</author>
		<author>F. Cazals</author>
		<author>J. Flötotto</author>
		<institution>INRIA Sophia Antipolis</institution>
		<citedby>10.1007/3-540-44541-2_11</citedby>
		<year>2000</year>
	</paper>
	<paper>
		<id>10.1007/3-540-44541-2_12</id>
		<title>Fast Layout Methods for Timetable Graphs</title>
		<author>Galina Shubina</author>
		<author>Dorothea Wagner</author>
		<author>Ulrik Brandes</author>
		<author>Roberto Tamassia</author>
		<institution>Brown University</institution>
		<institution>University of Konstanz</institution>
		<cites>10.1007/3-540-37623-2_12</cites>
		<cites>10.1007/3-540-37623-2_13</cites>
		<cites>10.1007/3-540-37623-2_28</cites>
		<cites>10.1007/3-540-46648-7_12</cites>
		<cites>10.1007/3-540-37623-2_4</cites>
		<cites>10.1007/3-540-63938-1_68</cites>
		<citedby>10.1007/978-3-540-31843-9_46</citedby>
		<year>2000</year>
	</paper>
	<paper>
		<id>10.1007/3-540-44541-2_13</id>
		<title>An Algorithmic Framework for Visualizing Statecharts</title>
		<author>R. Mili</author>
		<author>R. Castelló</author>
		<author>I. G. Tollis</author>
		<institution>The University of Texas at Dallas</institution>
		<cites>10.1007/3-540-63938-1_60</cites>
		<cites>10.1007/3-540-62495-3_52</cites>
		<cites>10.1007/3-540-62495-3_42</cites>
		<cites>10.1007/3-540-63938-1_58</cites>
		<cites>10.1007/3-540-63938-1_86</cites>
		<citedby>10.1007/3-540-36151-0_7</citedby>
		<citedby>10.1007/3-540-45848-4_56</citedby>
		<year>2000</year>
	</paper>
	<paper>
		<id>10.1007/3-540-44541-2_14</id>
		<title>Visualization of the Autonomous Systems Interconnections with Hermes</title>
		<author>Maurizio Pizzonia</author>
		<author>Andrea Carmignani</author>
		<author>Giuseppe Di Battista</author>
		<author>Walter Didimo</author>
		<author>Francesco Matera</author>
		<institution>Università di Roma Tre</institution>
		<cites>10.1007/BFb0021809</cites>
		<cites>10.1007/3-540-37623-2_5</cites>
		<cites>10.1007/BFb0021824</cites>
		<cites>10.1007/3-540-63938-1_77</cites>
		<cites>10.1007/3-540-46648-7_31</cites>
		<citedby>10.1007/3-540-45848-4_38</citedby>
		<citedby>10.1007/978-3-540-77537-9_36</citedby>
		<year>2000</year>
	</paper>
	<paper>
		<id>10.1007/3-540-44541-2_15</id>
		<title>Drawing Hypergraphs in the Subset Standard (Short Demo Paper)</title>
		<author>Peter Eades</author>
		<author>François Bertault</author>
		<institution>The University of Sydney</institution>
		<institution>Tom Sawyer Software</institution>
		<cites>10.1007/3-540-36151-0_43</cites>
		<year>2000</year>
	</paper>
	<paper>
		<id>10.1007/3-540-44541-2_16</id>
		<title>Knowledge Discovery from Graphs</title>
		<author>David Jensen</author>
		<institution>University of Massachusetts</institution>
		<year>2000</year>
	</paper>
	<paper>
		<id>10.1007/3-540-44541-2_17</id>
		<title>A Multilevel Algorithm for Force-Directed Graph Drawing</title>
		<author>C. Walshaw</author>
		<institution>University of Greenwich</institution>
		<cites>10.1007/3-540-46648-7_19</cites>
		<cites>10.1007/3-540-62495-3_41</cites>
		<cites>10.1007/3-540-62495-3_42</cites>
		<citedby>10.1007/11618058_22</citedby>
		<citedby>10.1007/978-3-540-70904-6_5</citedby>
		<citedby>10.1007/11618058_31</citedby>
		<citedby>10.1007/978-3-642-00219-9_10</citedby>
		<citedby>10.1007/978-3-540-24595-7_40</citedby>
		<citedby>10.1007/978-3-540-31843-9_44</citedby>
		<citedby>10.1007/3-540-36151-0_20</citedby>
		<citedby>10.1007/3-540-36151-0_35</citedby>
		<citedby>10.1007/978-3-319-03841-4_24</citedby>
		<citedby>10.1007/3-540-44541-2_17</citedby>
		<citedby>10.1007/11618058_28</citedby>
		<citedby>10.1007/978-3-540-31843-9_25</citedby>
		<citedby>10.1007/978-3-540-31843-9_29</citedby>
		<citedby>10.1007/978-3-642-00219-9_19</citedby>
		<year>2000</year>
	</paper>
	<paper>
		<id>10.1007/3-540-44541-2_18</id>
		<title>A Fast Multi-scale Method for Drawing Large Graphs</title>
		<author>Yehuda Koren</author>
		<author>David Harel</author>
		<institution>The Weizmann Institute of Science</institution>
		<cites>10.1007/BFb0021792</cites>
		<citedby>10.1007/11618058_22</citedby>
		<citedby>10.1007/978-3-540-70904-6_5</citedby>
		<citedby>10.1007/978-3-540-24595-7_42</citedby>
		<citedby>10.1007/978-3-642-00219-9_10</citedby>
		<citedby>10.1007/978-3-540-24595-7_40</citedby>
		<citedby>10.1007/978-3-540-31843-9_44</citedby>
		<citedby>10.1007/3-540-44541-2_19</citedby>
		<citedby>10.1007/3-540-36151-0_20</citedby>
		<citedby>10.1007/978-3-642-00219-9_20</citedby>
		<citedby>10.1007/978-3-642-36763-2_2</citedby>
		<citedby>10.1007/978-3-319-27261-0_2</citedby>
		<citedby>10.1007/978-3-662-45803-7_20</citedby>
		<citedby>10.1007/11618058_28</citedby>
		<citedby>10.1007/978-3-540-31843-9_25</citedby>
		<citedby>10.1007/3-540-44541-2_20</citedby>
		<citedby>10.1007/978-3-540-31843-9_29</citedby>
		<citedby>10.1007/3-540-44541-2_21</citedby>
		<year>2000</year>
	</paper>
	<paper>
		<id>10.1007/3-540-44541-2_10</id>
		<title>How to Draw the Minimum Cuts of a Planar Graph</title>
		<author>Sabine Cornelsen</author>
		<author>Dorothea Wagner</author>
		<author>Ulrik Brandes</author>
		<institution>University of Konstanz</institution>
		<cites>10.1007/3-540-63938-1_58</cites>
		<cites>10.1007/3-540-37623-2_44</cites>
		<cites>10.1007/3-540-62495-3_49</cites>
		<citedby>10.1007/978-3-540-24595-7_33</citedby>
		<citedby>10.1007/3-540-45848-4_5</citedby>
		<citedby>10.1007/978-3-642-25878-7_12</citedby>
		<year>2000</year>
	</paper>
	<paper>
		<id>10.1007/3-540-62495-3_60</id>
		<title>A pairing technique for area-efficient orthogonal drawings (extended abstract)</title>
		<author>Ioannis G. Tollis</author>
		<author>Achilleas Papakostas</author>
		<institution>The University of Texas at Dallas</institution>
		<cites>10.1007/3-540-58950-3_355</cites>
		<cites>10.1007/BFb0021788</cites>
		<cites>10.1007/3-540-58950-3_384</cites>
		<year>1996</year>
	</paper>
	<paper>
		<id>10.1007/3-540-62495-3_61</id>
		<title>Experimental and theoretical results in interactive orthogonal graph drawing</title>
		<author>Janet M. Six</author>
		<author>Ioannis G. Tollis</author>
		<author>Achilleas Papakostas</author>
		<institution>The University of Texas at Dallas</institution>
		<cites>10.1007/3-540-58950-3_355</cites>
		<citedby>10.1007/3-540-63938-1_73</citedby>
		<citedby>10.1007/3-540-63938-1_84</citedby>
		<citedby>10.1007/3-540-37623-2_23</citedby>
		<citedby>10.1007/3-540-45848-4_19</citedby>
		<citedby>10.1007/3-540-63938-1_55</citedby>
		<citedby>10.1007/3-540-37623-2_1</citedby>
		<year>1996</year>
	</paper>
	<paper>
		<id>10.1007/3-540-62495-3_62</id>
		<title>An interactive system for drawing graphs</title>
		<author>Kathy Ryall</author>
		<author>Joe Marks</author>
		<author>Stuart Shieber</author>
		<institution>Mitsubishi Electric Research Laboratories</institution>
		<institution>Harvard University</institution>
		<citedby>10.1007/978-3-642-00219-9_27</citedby>
		<citedby>10.1007/3-540-63938-1_73</citedby>
		<citedby>10.1007/3-540-44541-2_23</citedby>
		<citedby>10.1007/3-540-45848-4_4</citedby>
		<citedby>10.1007/3-540-44541-2_3</citedby>
		<citedby>10.1007/3-540-36151-0_1</citedby>
		<citedby>10.1007/3-540-37623-2_5</citedby>
		<citedby>10.1007/3-540-45848-4_55</citedby>
		<year>1996</year>
	</paper>
	<paper>
		<id>10.1007/3-540-62495-3_63</id>
		<title>Automatic graph clustering (system demonstration)</title>
		<author>Reinhard Sablowski</author>
		<author>Arne Frick</author>
		<institution>Tom Sawyer Software</institution>
		<institution>Universität Karlsruhe</institution>
		<cites>10.1007/3-540-58950-3_395</cites>
		<citedby>10.1007/3-540-44541-2_19</citedby>
		<year>1996</year>
	</paper>
	<paper>
		<id>10.1007/3-540-62495-3_64</id>
		<title>Qualitative visualization of processes: Attributed graph layout and focusing techniques</title>
		<author>Kent Wittenburg</author>
		<author>Louis Weitzman</author>
		<institution>Meta Media Design</institution>
		<institution>Bell Communications Research</institution>
		<cites>10.1007/3-540-58950-3_379</cites>
		<cites>10.1007/978-3-642-25878-7_9</cites>
		<cites>10.1007/3-540-58950-3_395</cites>
		<cites>10.1007/3-540-58950-3_373</cites>
		<cites>10.1007/3-540-58950-3_371</cites>
		<citedby>10.1007/3-540-45848-4_4</citedby>
		<year>1996</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_387</id>
		<title>Upward drawing on the plane grid using less ink</title>
		<author>Guy Vincent Jourdan</author>
		<author>Ivan Rival</author>
		<author>Nejib Zaguia</author>
		<institution>IRISA</institution>
		<institution>University of Ottawa</institution>
		<citedby>10.1007/978-3-642-25878-7_2</citedby>
		<year>1994</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_388</id>
		<title>Proximity drawability: A survey extended abstract</title>
		<author>Giuseppe Di Battista</author>
		<author>Giuseppe Liotta</author>
		<author>William Lenhart</author>
		<institution>Williams College</institution>
		<institution>Università di Roma “La Sapienza”</institution>
		<year>1994</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_385</id>
		<title>Upward planarity testing of outerplanar dags (extended abstract)</title>
		<author>Achilleas Papakostas</author>
		<institution>The University of Texas at Dallas</institution>
		<cites>10.1007/3-540-58950-3_384</cites>
		<citedby>10.1007/978-3-642-36763-2_22</citedby>
		<year>1994</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_386</id>
		<title>Optimal-area upward drawings of AVL trees</title>
		<author>P. Crescenzi</author>
		<author>A. Piperno</author>
		<institution>Università di Roma “La Sapienza”</institution>
		<citedby>10.1007/BFb0021791</citedby>
		<citedby>10.1007/3-540-63938-1_82</citedby>
		<citedby>10.1007/3-540-63938-1_47</citedby>
		<citedby>10.1007/3-540-62495-3_38</citedby>
		<year>1994</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_389</id>
		<title>Proximity constraints and representable trees (extended abstract)</title>
		<author>Prosenjit Bose</author>
		<author>Giuseppe Di Battista</author>
		<author>Giuseppe Liotta</author>
		<author>William Lenhart</author>
		<institution>Università di Roma “La Sapienza”</institution>
		<institution>Williams College</institution>
		<institution>McGill University</institution>
		<year>1994</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_380</id>
		<title>CG: A graph drawing system using graph-grammar parsing</title>
		<author>Fwu Shan Shieh</author>
		<author>Carolyn McCreary</author>
		<author>Helen Gill</author>
		<institution>McLean</institution>
		<institution>Auburn University</institution>
		<citedby>10.1007/BFb0021831</citedby>
		<year>1994</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_383</id>
		<title>Molecular graph eigenvectors for molecular coordinates</title>
		<author>Patrick W. Fowler</author>
		<author>Tomaž Pisanski</author>
		<author>John Shawe Taylor</author>
		<institution>University of Ljubljana</institution>
		<institution>University of Exeter</institution>
		<institution>University of London</institution>
		<citedby>10.1007/BFb0021823</citedby>
		<year>1994</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_384</id>
		<title>On the computational complexity of upward and rectilinear planarity testing</title>
		<author>Ashim Garg</author>
		<author>Roberto Tamassia</author>
		<institution>Brown University</institution>
		<citedby>10.1007/3-540-63938-1_74</citedby>
		<citedby>10.1007/978-3-642-00219-9_24</citedby>
		<citedby>10.1007/978-3-642-25878-7_40</citedby>
		<citedby>10.1007/BFb0021790</citedby>
		<citedby>10.1007/978-3-319-03841-4_1</citedby>
		<citedby>10.1007/978-3-319-03841-4_2</citedby>
		<citedby>10.1007/3-540-46648-7_4</citedby>
		<citedby>10.1007/978-3-319-03841-4_4</citedby>
		<citedby>10.1007/3-540-46648-7_2</citedby>
		<citedby>10.1007/978-3-540-24595-7_36</citedby>
		<citedby>10.1007/978-3-642-25878-7_2</citedby>
		<citedby>10.1007/3-540-62495-3_44</citedby>
		<citedby>10.1007/3-540-58950-3_385</citedby>
		<citedby>10.1007/978-3-642-36763-2_10</citedby>
		<citedby>10.1007/978-3-642-36763-2_14</citedby>
		<citedby>10.1007/978-3-642-36763-2_15</citedby>
		<citedby>10.1007/978-3-642-25878-7_39</citedby>
		<citedby>10.1007/11618058_37</citedby>
		<citedby>10.1007/3-540-58950-3_384</citedby>
		<citedby>10.1007/3-540-62495-3_49</citedby>
		<citedby>10.1007/BFb0021798</citedby>
		<citedby>10.1007/978-3-662-45803-7_28</citedby>
		<citedby>10.1007/978-3-662-45803-7_29</citedby>
		<citedby>10.1007/978-3-540-24595-7_24</citedby>
		<citedby>10.1007/978-3-642-11805-0_5</citedby>
		<citedby>10.1007/3-540-63938-1_64</citedby>
		<citedby>10.1007/978-3-642-36763-2_21</citedby>
		<citedby>10.1007/BFb0021809</citedby>
		<citedby>10.1007/3-540-58950-3_375</citedby>
		<citedby>10.1007/978-3-642-36763-2_22</citedby>
		<citedby>10.1007/3-540-37623-2_13</citedby>
		<citedby>10.1007/978-3-540-31843-9_14</citedby>
		<citedby>10.1007/978-3-662-45803-7_35</citedby>
		<citedby>10.1007/978-3-662-45803-7_34</citedby>
		<citedby>10.1007/978-3-662-45803-7_32</citedby>
		<citedby>10.1007/978-3-642-18469-7_28</citedby>
		<citedby>10.1007/11618058_10</citedby>
		<citedby>10.1007/3-540-45848-4_31</citedby>
		<citedby>10.1007/978-3-540-24595-7_55</citedby>
		<citedby>10.1007/3-540-62495-3_60</citedby>
		<citedby>10.1007/3-540-63938-1_58</citedby>
		<citedby>10.1007/3-540-63938-1_55</citedby>
		<citedby>10.1007/3-540-63938-1_56</citedby>
		<citedby>10.1007/3-540-63938-1_54</citedby>
		<citedby>10.1007/978-3-319-03841-4_35</citedby>
		<citedby>10.1007/978-3-642-11805-0_23</citedby>
		<citedby>10.1007/3-540-44541-2_28</citedby>
		<citedby>10.1007/978-3-319-03841-4_37</citedby>
		<citedby>10.1007/BFb0021811</citedby>
		<citedby>10.1007/978-3-662-45803-7_23</citedby>
		<citedby>10.1007/978-3-642-25878-7_12</citedby>
		<citedby>10.1007/11618058_12</citedby>
		<citedby>10.1007/978-3-642-00219-9_30</citedby>
		<citedby>10.1007/978-3-642-18469-7_2</citedby>
		<citedby>10.1007/3-540-37623-2_2</citedby>
		<citedby>10.1007/3-540-58950-3_355</citedby>
		<citedby>10.1007/BFb0021825</citedby>
		<citedby>10.1007/978-3-642-18469-7_9</citedby>
		<citedby>10.1007/3-540-58950-3_356</citedby>
		<citedby>10.1007/BFb0021788</citedby>
		<citedby>10.1007/3-540-58950-3_394</citedby>
		<citedby>10.1007/978-3-540-77537-9_20</citedby>
		<year>1994</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_381</id>
		<title>A demonstration of interactive graph based visual language applications</title>
		<author>Jeffrey D. McWhirter</author>
		<institution>University of Colorado</institution>
		<year>1994</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_382</id>
		<title>A simple algorithm for drawing large graphs on small screens</title>
		<author>Karlis Kaugars</author>
		<author>Juris Reinfelds</author>
		<author>Alvis Brazma</author>
		<institution>University of Latvia</institution>
		<institution>New Mexico State University</institution>
		<citedby>10.1007/BFb0021803</citedby>
		<citedby>10.1007/3-540-46648-7_39</citedby>
		<citedby>10.1007/3-540-37623-2_9</citedby>
		<citedby>10.1007/978-3-642-36763-2_6</citedby>
		<citedby>10.1007/3-540-44541-2_20</citedby>
		<citedby>10.1007/BFb0021797</citedby>
		<year>1994</year>
	</paper>
	<paper>
		<id>10.1007/BFb0021808</id>
		<title>Generalized fisheye views of graphs</title>
		<author>Jörg Keller</author>
		<author>Arno Formella</author>
		<institution>Universität des Saarlandes</institution>
		<year>1995</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_376</id>
		<title>Redrawing a graph within a geometric tolerance</title>
		<author>Manuel Abellanas</author>
		<author>Ferran Hurtado</author>
		<author>Pedro A. Ramos</author>
		<institution>Universitat Politécnica de Catalunya</institution>
		<institution>Universitat Politécnica de Madrid</institution>
		<year>1994</year>
	</paper>
	<paper>
		<id>10.1007/BFb0021807</id>
		<title>New results on a visibility representation of graphs in 3D</title>
		<author>Sue Whitesides</author>
		<author>Sándor P. Fekete</author>
		<author>Michael E. Houle</author>
		<institution>McGill University</institution>
		<institution>University of Newcastle</institution>
		<institution>Universität zu Köln</institution>
		<cites>10.1007/3-540-58950-3_369</cites>
		<cites>10.1007/BFb0021785</cites>
		<cites>10.1007/3-540-58950-3_351</cites>
		<citedby>10.1007/3-540-37623-2_25</citedby>
		<citedby>10.1007/3-540-63938-1_52</citedby>
		<citedby>10.1007/3-540-62495-3_55</citedby>
		<citedby>10.1007/978-3-319-27261-0_31</citedby>
		<citedby>10.1007/3-540-46648-7_34</citedby>
		<citedby>10.1007/978-3-642-11805-0_31</citedby>
		<citedby>10.1007/BFb0021799</citedby>
		<citedby>10.1007/3-540-63938-1_69</citedby>
		<citedby>10.1007/978-3-540-24595-7_21</citedby>
		<citedby>10.1007/BFb0021785</citedby>
		<year>1995</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_377</id>
		<title>On the difficulty of embedding planar graphs with inaccuracies</title>
		<author>Michael Godau</author>
		<institution>Freie Universität Berlin</institution>
		<citedby>10.1007/978-3-662-45803-7_34</citedby>
		<citedby>10.1007/978-3-540-24595-7_14</citedby>
		<year>1994</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_374</id>
		<title>TOSCANA — A graphical tool for analyzing and exploring data</title>
		<author>Rudolf Wille</author>
		<author>Frank Vogt</author>
		<institution>Technische Hochschule Darmstadt</institution>
		<citedby>10.1007/BFb0021832</citedby>
		<year>1994</year>
	</paper>
	<paper>
		<id>10.1007/BFb0021809</id>
		<title>Drawing high degree graphs with low bend numbers</title>
		<author>Ulrich Fößmeier</author>
		<author>Michael Kaufmann</author>
		<institution>Universität Tübingen</institution>
		<cites>10.1007/3-540-58950-3_384</cites>
		<citedby>10.1007/3-540-63938-1_52</citedby>
		<citedby>10.1007/3-540-44541-2_5</citedby>
		<citedby>10.1007/978-3-540-70904-6_33</citedby>
		<citedby>10.1007/3-540-36151-0_31</citedby>
		<citedby>10.1007/3-540-63938-1_57</citedby>
		<citedby>10.1007/3-540-63938-1_79</citedby>
		<citedby>10.1007/978-3-540-24595-7_33</citedby>
		<citedby>10.1007/3-540-36151-0_33</citedby>
		<citedby>10.1007/3-540-46648-7_3</citedby>
		<citedby>10.1007/3-540-36151-0_6</citedby>
		<citedby>10.1007/3-540-45848-4_12</citedby>
		<citedby>10.1007/3-540-45848-4_11</citedby>
		<citedby>10.1007/3-540-46648-7_2</citedby>
		<citedby>10.1007/3-540-62495-3_45</citedby>
		<citedby>10.1007/978-3-642-36763-2_14</citedby>
		<citedby>10.1007/3-540-36151-0_1</citedby>
		<citedby>10.1007/978-3-319-03841-4_37</citedby>
		<citedby>10.1007/3-540-37623-2_28</citedby>
		<citedby>10.1007/11618058_36</citedby>
		<citedby>10.1007/3-540-45848-4_5</citedby>
		<citedby>10.1007/978-3-642-25878-7_12</citedby>
		<citedby>10.1007/3-540-63938-1_84</citedby>
		<citedby>10.1007/978-3-642-18469-7_15</citedby>
		<citedby>10.1007/978-3-540-31843-9_24</citedby>
		<citedby>10.1007/978-3-642-18469-7_31</citedby>
		<citedby>10.1007/3-540-46648-7_32</citedby>
		<citedby>10.1007/3-540-37623-2_3</citedby>
		<citedby>10.1007/3-540-63938-1_88</citedby>
		<citedby>10.1007/3-540-46648-7_31</citedby>
		<citedby>10.1007/978-3-540-70904-6_25</citedby>
		<citedby>10.1007/3-540-44541-2_14</citedby>
		<citedby>10.1007/BFb0021809</citedby>
		<citedby>10.1007/978-3-540-31843-9_39</citedby>
		<year>1995</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_375</id>
		<title>Characterization and recognition of point-halfspace and related orders</title>
		<author>Paul J. Tanenbaum</author>
		<author>Edward R. Scheinerman</author>
		<author>Michael T. Goodrich</author>
		<institution>U.S. Army Research Laboratory</institution>
		<institution>The Johns Hopkins University</institution>
		<cites>10.1007/3-540-58950-3_384</cites>
		<year>1994</year>
	</paper>
	<paper>
		<id>10.1007/BFb0021804</id>
		<title>Vertex splitting and tension-free layout</title>
		<author>Candido F. X. de Mendonça Neto</author>
		<author>Peter Eades</author>
		<institution>University of Newcastle</institution>
		<institution>Unicamp</institution>
		<citedby>10.1007/978-3-540-24595-7_41</citedby>
		<year>1995</year>
	</paper>
	<paper>
		<id>10.1007/BFb0021803</id>
		<title>COMAIDE: Information visualization using cooperative 3D diagram layout</title>
		<author>David Dodson</author>
		<institution>City University</institution>
		<cites>10.1007/3-540-58950-3_396</cites>
		<cites>10.1007/3-540-58950-3_382</cites>
		<citedby>10.1007/3-540-63938-1_70</citedby>
		<citedby>10.1007/3-540-37623-2_7</citedby>
		<citedby>10.1007/3-540-62495-3_48</citedby>
		<citedby>10.1007/3-540-36151-0_14</citedby>
		<year>1995</year>
	</paper>
	<paper>
		<id>10.1007/BFb0021806</id>
		<title>Graph-Drawing contest report</title>
		<author>Joe Marks</author>
		<author>Peter Eades</author>
		<institution>University of Newcastle</institution>
		<institution>Mitsubishi Electric Research Laboratories</institution>
		<year>1995</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_378</id>
		<title>A system for drawing graphs with geometric symmetry</title>
		<author>Mikhail Atallah</author>
		<author>Joseph Manning</author>
		<author>Kingsley Cudjoe</author>
		<author>Joe Lozito</author>
		<author>Ron Pacheco</author>
		<institution>Vassar College</institution>
		<institution>Purdue University</institution>
		<institution>Harding University</institution>
		<citedby>10.1007/3-540-44541-2_35</citedby>
		<year>1994</year>
	</paper>
	<paper>
		<id>10.1007/BFb0021805</id>
		<title>Drawing stressed planar graphs in three dimensions</title>
		<author>Patrick Garvan</author>
		<author>Peter Eades</author>
		<institution>University of Newcastle</institution>
		<cites>10.1007/3-540-58950-3_351</cites>
		<citedby>10.1007/3-540-37623-2_25</citedby>
		<citedby>10.1007/3-540-62495-3_55</citedby>
		<citedby>10.1007/978-3-319-03841-4_16</citedby>
		<citedby>10.1007/3-540-36151-0_5</citedby>
		<citedby>10.1007/978-3-642-11805-0_6</citedby>
		<year>1995</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_379</id>
		<title>Demonstration of the interactive graph visualization system da Vinci</title>
		<author>Mattias Werner</author>
		<author>Michael Fröhlich</author>
		<institution>University of Bremen</institution>
		<cites>10.1007/978-3-642-25878-7_9</cites>
		<cites>10.1007/3-540-58950-3_371</cites>
		<citedby>10.1007/978-3-319-27261-0_51</citedby>
		<citedby>10.1007/3-540-62495-3_64</citedby>
		<citedby>10.1007/3-540-37623-2_30</citedby>
		<year>1994</year>
	</paper>
	<paper>
		<id>10.1007/BFb0021800</id>
		<title>3D graph drawing with simulated annealing</title>
		<author>Isabel F. Cruz</author>
		<author>Joseph P. Twarog</author>
		<institution>Tufts University</institution>
		<cites>10.1007/3-540-58950-3_353</cites>
		<cites>10.1007/978-3-642-25878-7_9</cites>
		<cites>10.1007/3-540-58950-3_351</cites>
		<citedby>10.1007/3-540-63938-1_50</citedby>
		<citedby>10.1007/3-540-63938-1_70</citedby>
		<citedby>10.1007/3-540-37623-2_19</citedby>
		<citedby>10.1007/3-540-37623-2_7</citedby>
		<citedby>10.1007/3-540-36151-0_5</citedby>
		<citedby>10.1007/3-540-62495-3_48</citedby>
		<citedby>10.1007/3-540-36151-0_14</citedby>
		<year>1995</year>
	</paper>
	<paper>
		<id>10.1007/BFb0021802</id>
		<title>The strength of weak proximity (extended abstract)</title>
		<author>Sue Whitesides</author>
		<author>Giuseppe Di Battista</author>
		<author>Giuseppe Liotta</author>
		<institution>Brown University</institution>
		<institution>Università di Roma Tre</institution>
		<institution>McGill University</institution>
		<year>1995</year>
	</paper>
	<paper>
		<id>10.1007/BFb0021801</id>
		<title>The botanical beauty of random binary trees</title>
		<author>Paul Kruszewski</author>
		<author>Luc Devroye</author>
		<institution>McGill University</institution>
		<year>1995</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_372</id>
		<title>Drawing telecommunication networks</title>
		<author>Ioannis G. Tollis</author>
		<author>Chunliang Xia</author>
		<institution>The University of Texas at Dallas</institution>
		<cites>10.1007/3-540-45848-4_36</cites>
		<citedby>10.1007/978-3-540-24595-7_13</citedby>
		<citedby>10.1007/3-540-46648-7_24</citedby>
		<citedby>10.1007/3-540-46648-7_11</citedby>
		<year>1994</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_373</id>
		<title>Reduction of visual complexity in dynamic graphs</title>
		<author>Bruce Leban</author>
		<author>Doug Kimelman</author>
		<author>Tova Roth</author>
		<author>Dror Zernik</author>
		<institution>IBM Research</institution>
		<cites>10.1007/3-540-45848-4_56</cites>
		<citedby>10.1007/3-540-46648-7_39</citedby>
		<citedby>10.1007/3-540-62495-3_64</citedby>
		<citedby>10.1007/3-540-37623-2_30</citedby>
		<year>1994</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_370</id>
		<title>GraphEd: A graphical platform for the implementation of graph algorithms (extended abstract and demo)</title>
		<author>Michael Himsolt</author>
		<institution>Universität Passau</institution>
		<cites>10.1007/978-3-642-25878-7_9</cites>
		<citedby>10.1007/3-540-63938-1_79</citedby>
		<year>1994</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_371</id>
		<title>Graph layout through the VCG tool</title>
		<author>Georg Sander</author>
		<institution>Universität des Saarlandes</institution>
		<citedby>10.1007/3-540-46648-7_8</citedby>
		<citedby>10.1007/3-540-63938-1_72</citedby>
		<citedby>10.1007/978-3-540-24595-7_35</citedby>
		<citedby>10.1007/3-540-63938-1_79</citedby>
		<citedby>10.1007/978-3-642-18469-7_13</citedby>
		<citedby>10.1007/3-540-36151-0_13</citedby>
		<citedby>10.1007/3-540-36151-0_36</citedby>
		<citedby>10.1007/BFb0021829</citedby>
		<citedby>10.1007/3-540-62495-3_46</citedby>
		<citedby>10.1007/3-540-45848-4_3</citedby>
		<citedby>10.1007/3-540-62495-3_51</citedby>
		<citedby>10.1007/BFb0021828</citedby>
		<citedby>10.1007/3-540-62495-3_64</citedby>
		<citedby>10.1007/3-540-58950-3_379</citedby>
		<citedby>10.1007/978-3-642-11805-0_14</citedby>
		<citedby>10.1007/978-3-540-31843-9_17</citedby>
		<year>1994</year>
	</paper>
	<paper>
		<id>10.1007/BFb0021819</id>
		<title>Layout algorithms of graph-like diagrams for GRADE windows graphic editors</title>
		<author>Paulis Ķikusts</author>
		<author>Pēteris Ručevskis</author>
		<institution>University of Latvia</institution>
		<citedby>10.1007/3-540-45848-4_4</citedby>
		<year>1995</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_365</id>
		<title>Graph-drawing contest report</title>
		<author>Joe Marks</author>
		<author>Peter Eades</author>
		<institution>Mitsubishi Electric Research Laboratories</institution>
		<institution>University of Newcastle University</institution>
		<year>1994</year>
	</paper>
	<paper>
		<id>10.1007/BFb0021818</id>
		<title>Constraint-based spring-model algorithm for graph layout</title>
		<author>Thomas Kamps</author>
		<author>John Read</author>
		<author>Joerg Kleinz</author>
		<institution>University of Waterloo</institution>
		<institution>GMD-IPSI</institution>
		<cites>10.1007/3-540-58950-3_391</cites>
		<cites>10.1007/3-540-58950-3_392</cites>
		<citedby>10.1007/3-540-62495-3_50</citedby>
		<citedby>10.1007/3-540-37623-2_28</citedby>
		<year>1995</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_366</id>
		<title>Visibility graphs and oriented matroids (extended abstract)</title>
		<author>James Abello</author>
		<author>Krishna Kumar</author>
		<institution>Texas A&amp;M University</institution>
		<institution>Colby College</institution>
		<year>1994</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_363</id>
		<title>The polyhedral approach to the maximum planar subgraph problem: New chances for related problems</title>
		<author>Michael Jünger</author>
		<author>Petra Mutzel</author>
		<institution>Universität zu Köln</institution>
		<citedby>10.1007/3-540-45848-4_6</citedby>
		<year>1994</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_364</id>
		<title>Crossing numbers of graphs, lower bound techniques and algorithms: A survey</title>
		<author>László A. Székely</author>
		<author>Farhad Shahrokhi</author>
		<author>Imrich Vrto</author>
		<institution>University of North Texas</institution>
		<institution>Eötvös University</institution>
		<institution>Slovak Academy of Sciences</institution>
		<citedby>10.1007/3-540-37623-2_18</citedby>
		<citedby>10.1007/978-3-540-77537-9_16</citedby>
		<citedby>10.1007/3-540-63938-1_48</citedby>
		<citedby>10.1007/BFb0021830</citedby>
		<year>1994</year>
	</paper>
	<paper>
		<id>10.1007/BFb0021815</id>
		<title>On representations of some thickness-two graphs</title>
		<author>Andrew Vince</author>
		<author>Joan P. Hutchinson</author>
		<author>Thomas Shermer</author>
		<institution>Macalester College</institution>
		<institution>University of Florida</institution>
		<institution>Simon Fraser University</institution>
		<cites>10.1007/3-540-58950-3_367</cites>
		<citedby>10.1007/3-540-44541-2_7</citedby>
		<citedby>10.1007/3-540-62495-3_35</citedby>
		<citedby>10.1007/978-3-642-00219-9_6</citedby>
		<citedby>10.1007/978-3-540-70904-6_32</citedby>
		<citedby>10.1007/BFb0021815</citedby>
		<citedby>10.1007/11618058_7</citedby>
		<citedby>10.1007/978-3-540-77537-9_32</citedby>
		<citedby>10.1007/3-540-63938-1_69</citedby>
		<citedby>10.1007/978-3-540-24595-7_21</citedby>
		<citedby>10.1007/978-3-642-25878-7_25</citedby>
		<citedby>10.1007/3-540-45848-4_33</citedby>
		<year>1995</year>
	</paper>
	<paper>
		<id>10.1007/3-540-58950-3_369</id>
		<title>Directed VR-representable graphs have unbounded dimension</title>
		<author>Kathleen Romanik</author>